//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public double Ratings_Mark { get; set; }
        public int Ratings_id_Users { get; set; }
        public int Ratings_id_Resource { get; set; }
        public System.DateTime Rating_Date { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual User User { get; set; }
    }
}
