//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Ratings = new HashSet<Rating>();
            this.Resources = new HashSet<Resource>();
        }
    
        public int Id { get; set; }
        public string Users_Email { get; set; }
        public string Users_Password { get; set; }
        public int Users_id_Role { get; set; }
        public System.DateTime Users_Creation_Date { get; set; }
    
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Resource> Resources { get; set; }
        public virtual Role Role { get; set; }
    }
}
